language: elixir
elixir:
  - '1.12.1'
otp_release:
  - '24.0.2'

before_install:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  - source $HOME/.cargo/env

jobs:
  include:
    - elixir: '1.12.1'
      otp_release: '24.0.2'

    - elixir: '1.12.1'
      otp_release: '23.3.1'

    - elixir: '1.11.4'
      otp_release: '23.3.1'

    - elixir: '1.11.4'
      otp_release: '24.0.2'

    - elixir: '1.10.4'
      otp_release: '23.3.1'

    - elixir: '1.10.4'
      otp_release: '22.2.8'

    - elixir: '1.9.4'
      otp_release: '22.2.8'

    - elixir: '1.8.2'
      otp_release: '22.2.8'

    - elixir: '1.7.4'
      otp_release: '22.2.8'
